### Alhad Joshi | alhad.coep@gmail.com | +919980820403 | 26th Sept 2021 Morning Batch
### Numpy|Pandas assignment

In [2]:
import numpy as np

In [5]:
# Write a Python program to reverse an array
# (first element becomes last).
arr1 = np.arange(11)
arr1 = arr1[::-1]
arr1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [8]:
# Read ==> https://stackoverflow.com/questions/14415741/what-is-the-difference-between-numpys-array-and-asarray-functions
# Write a Python program to convert a list and tuple into arrays.
lst = [1,2,3,4,5]
tpl = (1,2,3,4,5)
lst_arr = np.array(lst)
tpl_arr = np.array(tpl)
print(lst_arr, tpl_arr)

[1 2 3 4 5] [1 2 3 4 5]


In [11]:
# Write a Python program to find common values between two arrays.
arr1 = np.arange(11)
arr2 = np.arange(5, 17)
np.intersect1d(arr1, arr2)

array([ 5,  6,  7,  8,  9, 10])

In [19]:
# Write a Python program compare two arrays using numpy.
# a = np.arange(11)
# b = np.arange(5, 17)
# print("a > b")
# print(np.greater(a,b)) --> ValueError: operands could not be broadcast together with shapes (11,) (12,) 

a = np.array([1, 2])
b = np.array([3, 2])
print("a > b")
print(np.greater(a,b))
print("a >= b")
print(np.greater_equal(a,b))
print("a < b")
print(np.less(a,b))
print("a <= b")
print(np.less_equal(a,b))

a > b
[False False]
a >= b
[False  True]
a < b
[ True False]
a <= b
[ True  True]


In [22]:
# Write a Python program to change the dimension of an array.
a = np.arange(10)
a = a.reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.
arr_3 = np.arange(0,101,3)
arr_5 = np.arange(0,101,5)
print(arr_3)
print(arr_5)
np.sum(np.union1d(arr_3, arr_5))

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


2418

In [30]:
# Write a Python program to convert a NumPy array into Python list structure.
arr1.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [39]:
# Write a Python program to how to add an extra column to a numpy array.
x = np.array([[10,20,30], [40,50,60]])
print(x.shape)
y = np.array([[100], [200]])
print(y.shape)
print(np.append(x,y)) # --> flattens if axis not given
# print(np.append(x,y,axis=0))
print(np.append(x,y,axis=1))

(2, 3)
(2, 1)
[ 10  20  30  40  50  60 100 200]
[[ 10  20  30 100]
 [ 40  50  60 200]]


In [46]:
# Write a Python program to check whether the numpy array is empty or not.
# np.empty((3,2,2))
arr1.size==0

False

In [63]:
# Write a Python program to normalize a 3x3 random matrix.
# np.random.random() # gives 1 number
x = np.random.random((3,3))
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
x

[[0.06088326 0.27385923 0.80612721]
 [0.09467008 0.88872033 0.39290966]
 [0.714813   0.30262218 0.38671941]]


array([[0.        , 0.25726798, 0.90023022],
       [0.04081337, 1.        , 0.40107698],
       [0.78992566, 0.29201268, 0.39359937]])

In [62]:
# How to swap two rows of an array?
x = np.random.random((3,3))
print(x)
y=x[:][1]
print(np.vstack(y, x[:][2]))

[[0.52389317 0.46573833 0.09995299]
 [0.42073721 0.56662416 0.55351394]
 [0.28462725 0.77435834 0.50026171]]


TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given