In [38]:
!pip install numpy

In [3]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [33]:
np_arr = np.array([[1,2],[3,4]])
print(np_arr.ndim)
print(np_arr|1) # bitwise operation on np array is possible
print(np_arr&1)
print(np_arr^1)

2
[[1 3]
 [3 5]]
[[1 0]
 [1 0]]
[[0 3]
 [2 5]]


In [12]:
new_arr = np_arr.reshape(1,2,2)
print(new_arr)
new_arr.ndim

[[[1 2]
  [3 4]]]


3

In [22]:
new_arr_1 = np_arr.reshape(1,2,-1)
print('shape=', new_arr_2.shape)
new_arr_1

shape= (1, 2, 2, 1)


array([[[1, 2],
        [3, 4]]])

In [21]:
new_arr_2 = np_arr.reshape(1,2,2,-1)
print('shape=', new_arr_2.shape)
print(new_arr_2)
new_arr_2.ndim

shape= (1, 2, 2, 1)
[[[[1]
   [2]]

  [[3]
   [4]]]]


4

In [25]:
new_arr_2 = np_arr.reshape(1,2,2,1,-1)
print('shape=', new_arr_2.shape)
print(new_arr_2)
new_arr_2.ndim

shape= (1, 2, 2, 1, 1)
[[[[[1]]

   [[2]]]


  [[[3]]

   [[4]]]]]


5

In [27]:
new_arr_2 = np_arr.reshape(1,2,2,1,1,-1)
print('shape=', new_arr_2.shape)
print(new_arr_2)
new_arr_2.ndim

shape= (1, 2, 2, 1, 1, 1)
[[[[[[1]]]


   [[[2]]]]



  [[[[3]]]


   [[[4]]]]]]


6

In [29]:
new_arr_2 = np_arr.reshape(1,2,2,1,1,1,-1)
print('shape=', new_arr_2.shape)
print(new_arr_2)
new_arr_2.ndim

shape= (1, 2, 2, 1, 1, 1, 1)
[[[[[[[1]]]]



   [[[[2]]]]]




  [[[[[3]]]]



   [[[[4]]]]]]]


7

In [37]:
print(np_arr)
print("\n")
print(np.sort(np_arr,axis=0)) # axis=0 is default
print("\n")
print(np.sort(np_arr,axis=1))
print("\n")
print(np.sort(np_arr,axis=None))

[[1 2]
 [3 4]]


[[1 2]
 [3 4]]


[[1 2]
 [3 4]]


[1 2 3 4]
